@startuml
class no.ntnu.tdt4240.project.powerup.strategy.ShieldPowerupStrategy {
+ void apply(PowerupEffectsComponent,float)
}

class no.ntnu.tdt4240.project.state.WaitingRoomState {
- {static} float VIEWPORT_MIN_WIDTH
- {static} float VIEWPORT_MIN_HEIGHT
- {static} float UPDATE_INTERVAL
- FirebaseController firebaseController
- Stage stage
- Table root
- Label playerCountLabel
- SpaceButton startBtn
- float updateTimer
- float pingTimer
- float pingInterval
- boolean inLobby
- boolean isHost
# void setup()
# void show()
- void showMainOptions()
- void createLobby()
- void showJoinInput()
- void joinLobby(String)
- void showWaitingRoom(boolean)
- void updateLobbyStatus()
# void update(float)
# void render()
# void resize(int,int)
# void hide()
+ void dispose()
}


class no.ntnu.tdt4240.project.state.GameState {
- {static} float PAUSE_BUTTON_COOLDOWN_SECONDS
- {static} int SABOTAGE_SCORE_THRESHOLD
- {static} int SABOTAGE_EFFECT_DURATION_SEC
- {static} int POWERUP_EFFECT_DURATION_SEC
- {static} float LOBBY_POLL_INTERVAL
- Engine engine
- Layout layout
- LobbyService lobbyService
- boolean gameOver
- GameHud hud
- boolean menuOpen
- boolean gameplayPaused
- InputMultiplexer inputMux
- boolean exitPauseWhenMenuCloses
- boolean hasBeenSetup
- float pauseButtonCooldownRemaining
- float lobbyPollTimer
- int sabotagesUsedCount
- int powerupsUsedCount
- Map<String,SabotageStrategy> sabotageStrategies
- Map<String,PowerupStrategy> powerupStrategies
+ void setup()
# void show()
# void hide()
- EventSystem eventSystem()
+ void receive(Event)
- int getPlayerScore()
- int getPlayerHealth()
~ Stage getHudStage()
~ void setExitPauseWhenMenuCloses(boolean)
+ boolean isMenuOpen()
+ void setMenuOpen(boolean)
~ void startPauseButtonCooldown()
- boolean isPauseButtonReady()
+ void renderFrozen()
- int getWaveNumber()
+ void resumeInput()
+ void update(float)
+ void updateGameplay(float)
+ void render()
+ int getAvailableAbilityCount()
+ void recordSabotageUse()
+ void recordPowerupUse()
+ boolean isMultiplayer()
+ void applyPowerup(String,float)
- PowerupEffectsComponent getPowerupEffectsComponent()
+ InputMultiplexer getInputMultiplexer()
+ void setGameplayPaused(boolean)
+ void restoreDefaultInput()
+ void sendSabotage(String)
+ void applySabotage(String,float)
- SabotageEffectsComponent getSabotageEffectsComponent()
+ void resize(int,int)
+ void dispose()
}


class no.ntnu.tdt4240.project.engine.system.RemovalSystem {
# void processEntity(Entity,float)
}

interface no.ntnu.tdt4240.project.powerup.strategy.PowerupStrategy {
~ void apply(PowerupEffectsComponent,float)
}

class no.ntnu.tdt4240.project.state.SettingsState {
- {static} float VIEWPORT_MIN_WIDTH
- {static} float VIEWPORT_MIN_HEIGHT
- {static} float BUTTON_SPACING
- {static} float FONT_SCALE_TITLE
- Stage stage
- boolean showingFirebase
# void setup()
- void buildLayout()
+ void update(float)
# void render()
+ void resize(int,int)
+ void dispose()
}


class no.ntnu.tdt4240.project.engine.component.EnemyComponent {
}
class no.ntnu.tdt4240.project.config.bullet.EnemyBullet {
- {static} float ENEMY_BULLET_VEL
+ NonPlayable create(Vector2,Vector2)
+ NonPlayable create(Vector2,Vector2,Vector2)
# Vector2 calculatePosition(Vector2,Vector2,float)
}


class no.ntnu.tdt4240.project.engine.system.ShootingSystem {
- PlayerBullet playerBullet
- EnemyBullet enemyBullet
- ImmutableArray<Entity> sabotageEntities
- ImmutableArray<Entity> powerupEntities
- ImmutableArray<Entity> players
+ void addedToEngine(com.badlogic.ashley.core.Engine)
# void processEntity(Entity,float)
}


class no.ntnu.tdt4240.project.state.LeaderboardState {
- {static} float VIEWPORT_MIN_WIDTH
- {static} float VIEWPORT_MIN_HEIGHT
- Stage stage
# void setup()
- void buildLayout()
+ void update(float)
# void render()
+ void resize(int,int)
+ void dispose()
}


abstract class no.ntnu.tdt4240.project.state.State {
# StateManager sm
# SpriteBatch batch
# Assets assets
# {abstract}void setup()
# void show()
# void hide()
# {abstract}void update(float)
# {abstract}void render()
# {abstract}void resize(int,int)
# {abstract}void dispose()
}


class no.ntnu.tdt4240.project.state.PowerupState {
- {static} float VIEWPORT_MIN_WIDTH
- {static} float VIEWPORT_MIN_HEIGHT
- {static} float POWERUP_UNPAUSE_TIMER_SEC
- {static} int POWERUP_EFFECT_DURATION_SEC
- {static} float BUTTON_HEIGHT
- {static} float BUTTON_GAP
- {static} float RETURN_BOTTOM_PAD
- {static} String GAME_NOT_PAUSED_LABEL
- GameState gameState
- Stage stage
- Texture overlayTex
- float unpauseTimeLeft
- boolean gameplayRunningBehindOverlay
- Label timerLabel
- Label chargesLabel
# void setup()
# void show()
- void buildLayout()
- void addPowerupRow(Table,String,String,boolean)
- void onPowerupChosen(String)
- void refreshChargesLabel()
- String formatChargesLine()
- {static} String formatUnpauseTimer(float)
- void onUnpauseTimerFinished()
- void attachGameplayInputBehindOverlay()
# void update(float)
# void render()
# void resize(int,int)
# void dispose()
}


class no.ntnu.tdt4240.project.engine.system.WaveSystem {
- {static} float WAVE_TRANSITION_DELAY
# void processEntity(Entity,float)
- void configureWave(WaveComponent)
}


interface no.ntnu.tdt4240.project.sabotage.strategy.SabotageStrategy {
~ void apply(SabotageEffectsComponent,float)
}

class no.ntnu.tdt4240.project.state.SabotageState {
- {static} float VIEWPORT_MIN_WIDTH
- {static} float VIEWPORT_MIN_HEIGHT
- {static} float SABOTAGE_UNPAUSE_TIMER_SEC
- {static} int SABOTAGE_EFFECT_DURATION_SEC
- {static} float BUTTON_HEIGHT
- {static} float BUTTON_GAP
- {static} float RETURN_BOTTOM_PAD
- {static} String GAME_NOT_PAUSED_LABEL
- GameState gameState
- Stage stage
- Texture overlayTex
- float unpauseTimeLeft
- boolean gameplayRunningBehindOverlay
- Label timerLabel
- Label chargesLabel
# void setup()
# void show()
- void buildLayout()
- void addSabotageRow(Table,String,String,boolean)
- void onSabotageChosen(String)
- void refreshChargesLabel()
- String formatChargesLine()
- {static} String formatUnpauseTimer(float)
- void onUnpauseTimerFinished()
- void attachGameplayInputBehindOverlay()
# void update(float)
# void render()
# void resize(int,int)
# void dispose()
}


class no.ntnu.tdt4240.project.sabotage.strategy.DoubleAliensSabotageStrategy {
+ void apply(SabotageEffectsComponent,float)
}

class no.ntnu.tdt4240.project.engine.component.PowerupEffectsComponent {
+ {static} float ENEMY_SPEED_SLOW_MULTIPLIER
+ {static} float PLAYER_SHOOT_INTERVAL_MULTIPLIER
+ float shieldRemaining
+ float rapidFireRemaining
+ float slowEnemiesRemaining
}

class no.ntnu.tdt4240.project.state.HistoryState {
- {static} float VIEWPORT_MIN_WIDTH
- {static} float VIEWPORT_MIN_HEIGHT
- Stage stage
# void setup()
- void buildLayout()
+ void update(float)
# void render()
+ void resize(int,int)
+ void dispose()
}


class no.ntnu.tdt4240.project.engine.Mapper {
+ {static} ComponentMapper<PositionComponent> position
+ {static} ComponentMapper<VelocityComponent> velocity
+ {static} ComponentMapper<DimensionComponent> dimension
+ {static} ComponentMapper<TextureComponent> texture
+ {static} ComponentMapper<HealthComponent> health
+ {static} ComponentMapper<ScoreComponent> score
+ {static} ComponentMapper<PlayerComponent> player
+ {static} ComponentMapper<EnemyComponent> enemy
+ {static} ComponentMapper<ShooterComponent> shooter
+ {static} ComponentMapper<BulletComponent> bullet
+ {static} ComponentMapper<SabotageEffectsComponent> sabotageEffects
+ {static} ComponentMapper<PowerupEffectsComponent> powerupEffects
+ {static} ComponentMapper<AnimationComponent> animation
+ {static} ComponentMapper<WaveComponent> wave
}

class no.ntnu.tdt4240.project.util.Theme {
+ Color background
+ Color primary
+ Color buttonIdle
+ Color buttonHover
+ Color buttonPressed
+ Color border
+ Color textSecondary
+ Color panelBackground
+ {static} float BUTTON_WIDTH
+ {static} float BUTTON_HEIGHT
+ {static} float BORDER_THICKNESS
+ {static} float FONT_SCALE_BUTTON
+ {static} float FONT_SCALE_SMALL
+ {static} Theme CLASSIC
}

class no.ntnu.tdt4240.project.engine.component.SabotageEffectsComponent {
+ {static} float ENEMY_SPEED_MULTIPLIER
+ {static} float PLAYER_SHOOT_INTERVAL_MULTIPLIER
+ {static} float ENEMY_SPAWN_RATE_MULTIPLIER
+ float enemySpeedBoostRemaining
+ float playerFireRateSlowRemaining
+ float alienSpawnBoostRemaining
}

class no.ntnu.tdt4240.project.data.Playable {
+ int health
}

class no.ntnu.tdt4240.project.sabotage.strategy.HalfPlayerBulletsSabotageStrategy {
+ void apply(SabotageEffectsComponent,float)
}

class no.ntnu.tdt4240.project.engine.system.PowerupEffectSystem {
# void processEntity(Entity,float)
- {static} float decToZero(float,float)
}

class no.ntnu.tdt4240.project.service.AudioService {
- {static} String PREFS_NAME
- {static} String PREF_MUSIC_VOLUME
- {static} String PREF_SOUND_VOLUME
- {static} AudioService instance
- float musicVolume
- float soundVolume
- Music currentMusic
- String currentMusicFile
- Preferences prefs
+ {static} AudioService getInstance()
+ void playMusic(String,boolean)
+ void stopMusic()
+ void playSound(Sound)
+ float getMusicVolume()
+ void setMusicVolume(float)
+ float getSoundVolume()
+ void setSoundVolume(float)
}


class no.ntnu.tdt4240.project.engine.component.TextureComponent {
+ TextureRegion region
}

class no.ntnu.tdt4240.project.engine.system.BounceSystem {
- ImmutableArray<Entity> players
- ImmutableArray<Entity> enemies
- PositionComponent pos
- VelocityComponent vel
- DimensionComponent dim
+ void addedToEngine(Engine)
+ void update(float)
- void playerBounce(Entity)
- void enemyBounce(Entity)
- void bounce(Runnable)
- boolean isLeftOutOfBounds()
- boolean isRightOutOfBounds()
}


class no.ntnu.tdt4240.project.engine.component.AnimationComponent {
+ TextureRegion[] frames
+ float frameDuration
+ float stateTime
}

class no.ntnu.tdt4240.project.state.StateManager {
- Stack<State> states
+ void push(State)
+ void pop()
+ void set(State)
+ void update(float)
+ void render()
+ void resize(int,int)
+ void dispose()
}


class no.ntnu.tdt4240.project.engine.system.EventSystem {
+ EventManager events
- HealthComponent component
# void processEntity(Entity,float)
- void process()
}


abstract class no.ntnu.tdt4240.project.layout.Layout {
# Stage stage
+ Stage get()
+ void resize(int,int)
# {abstract}void build()
}


class no.ntnu.tdt4240.project.util.FirebaseJson {
+ {static} String toFirestoreDocument(Object)
+ {static} String toJson(Object)
- {static} void appendFields(StringBuilder,Object,boolean)
- {static} void appendFirestoreValue(StringBuilder,Object)
- {static} void appendJsonValue(StringBuilder,Object)
- {static} String escapeJson(String)
}

class no.ntnu.tdt4240.project.layout.GameLayout {
+ void build()
}

class no.ntnu.tdt4240.project.config.bullet.PlayerBullet {
- {static} float PLAYER_BULLET_VEL
+ NonPlayable create(Vector2,Vector2)
# Vector2 calculatePosition(Vector2,Vector2,float)
}


class no.ntnu.tdt4240.project.powerup.strategy.SlowEnemiesPowerupStrategy {
+ void apply(PowerupEffectsComponent,float)
}

class no.ntnu.tdt4240.project.event.EventManager {
~ List<EventListener> listeners
+ void subscribe(EventListener)
+ void unsubscribe(EventListener)
+ void alert(Event)
}


class no.ntnu.tdt4240.project.ui.SpaceButton {
}
class no.ntnu.tdt4240.project.engine.component.RemoveComponent {
}
abstract class no.ntnu.tdt4240.project.config.bullet.Bullet {
# {static} float BULLET_WIDTH
# {static} float BULLET_HEIGHT
# TextureRegion tex
# TextureRegion[] frames
# {abstract}NonPlayable create(Vector2,Vector2)
# {abstract}Vector2 calculatePosition(Vector2,Vector2,float)
}


class no.ntnu.tdt4240.project.engine.component.ShooterComponent {
+ float baseInterval
+ float timer
}

class no.ntnu.tdt4240.project.engine.system.SpawnSystem {
- float baseInterval
- Enemy enemy
- ImmutableArray<com.badlogic.ashley.core.Entity> sabotageEntities
- ImmutableArray<com.badlogic.ashley.core.Entity> waveEntities
- float spawnTimer
+ void addedToEngine(com.badlogic.ashley.core.Engine)
+ void update(float)
}


class no.ntnu.tdt4240.project.config.Enemy {
- {static} float ENEMY_WIDTH
- {static} float ENEMY_HEIGHT
- {static} float ENEMY_VEL
- TextureRegion tex
- TextureRegion[] frames
- boolean spawnLeft
+ NonPlayable create()
- Vector2 calculatePosition(float)
}


class no.ntnu.tdt4240.project.model.Powerup {
+ {static} String TYPE_SHIELD
+ {static} String TYPE_RAPID_FIRE
+ {static} String TYPE_SLOW_ENEMIES
+ String type
+ int duration
}

class no.ntnu.tdt4240.project.engine.component.PositionComponent {
+ float x
}

class no.ntnu.tdt4240.project.ui.FirebaseTestWidget {
- {static} Color STATUS_SUCCESS
- {static} Color STATUS_ERROR
- {static} Color STATUS_PENDING
+ {static} String SERVICE_FUNCTIONS
+ {static} String SERVICE_FIRESTORE
+ {static} String SERVICE_DATABASE
- Label statusLabel
- Label.LabelStyle statusStyle
- String service
- {static} int SCALE
- void runTest()
- {static} TextureRegionDrawable createBackground(Theme)
}


class no.ntnu.tdt4240.project.Assets {
+ TextureRegion player
+ TextureRegion playerBullet
+ TextureRegion enemy
+ TextureRegion enemyBullet
+ TextureRegion[] playerFrames
+ TextureRegion[] playerBulletFrames
+ TextureRegion[] enemyFrames
+ TextureRegion[] enemyBulletFrames
- Texture playerSheet
- Texture playerBulletSheet
- Texture enemySheet
- Texture enemyBulletSheet
- Texture starsBackground
- Texture logoCrop
- BitmapFont defaultFont
- FreeTypeFontGenerator fontGenerator
- Sound laserSound
+ void load()
+ Texture getStarsBackground()
+ Texture getLogoCrop()
+ BitmapFont getDefaultFont()
+ Sound getLaserSound()
- {static} TextureRegion[] flattenFrames(TextureRegion[][])
+ {static} Texture createColorTexture(Color)
+ void dispose()
}


class no.ntnu.tdt4240.project.data.NonPlayable {
+ Vector2 vel
}

class no.ntnu.tdt4240.project.engine.system.SabotageEffectSystem {
# void processEntity(Entity,float)
- {static} float decToZero(float,float)
}

class no.ntnu.tdt4240.project.powerup.strategy.RapidFirePowerupStrategy {
+ void apply(PowerupEffectsComponent,float)
}

class no.ntnu.tdt4240.project.AppProperties {
+ {static} int WIDTH
+ {static} int HEIGHT
+ {static} String TITLE
}

class no.ntnu.tdt4240.project.engine.system.RenderSystem {
- TextureComponent tex
- PositionComponent pos
- DimensionComponent dim
- SpriteBatch batch
- Viewport viewport
+ void update(float)
+ void processEntity(Entity,float)
- float centerHorizontal()
- float centerVertical()
}


class no.ntnu.tdt4240.project.config.WaveConfig {
+ int enemyCount
+ float spawnInterval
+ float shooterChance
+ float speedMultiplier
+ {static} WaveConfig forWave(int)
}


class no.ntnu.tdt4240.project.data.LobbyPlayer {
+ String actualName
+ boolean inGameOverScreen
+ boolean gameOver
+ boolean leftLobby
+ Object lastTimeOnline
+ int personalHighScore
+ int score
+ Sabotage sabotage
+ String sabotageTargetId
}

enum no.ntnu.tdt4240.project.event.Event {
+  WIN
+  LOSE
}

class no.ntnu.tdt4240.project.service.FirebaseController {
- LobbyService lobbyService
+ LobbyService lobbyHandler()
+ void checkDatabaseFormat(LobbyService.LobbyCallback)
+ void createLobby(LobbyService.LobbyCallback)
+ void joinLobby(String,LobbyService.LobbyCallback)
+ void leaveLobby(LobbyService.LobbyCallback)
+ void getLobbyStatus(LobbyService.LobbyStatusCallback)
+ void startGame(LobbyService.LobbyCallback)
+ void pingGameHandler()
+ String getLobbyID()
}


class no.ntnu.tdt4240.project.ui.UiFactory {
- {static} UiFactory instance
- Skin skin
- BitmapFont font
- Theme theme
- int texCounter
- {static} int SCALE
+ {static} void init(BitmapFont)
+ {static} UiFactory getInstance()
+ Skin getSkin()
+ Theme getTheme()
+ void setTheme(Theme)
- void buildSkin()
- TextureRegionDrawable createBorderedDrawable(Color,Color,int,int,int)
- TextureRegionDrawable createSimpleDrawable(Color,int,int)
+ void dispose()
}


class no.ntnu.tdt4240.project.engine.system.InputSystem {
- PositionComponent pos
- GameInputProcessor input
# void processEntity(Entity,float)
- void process()
}


class no.ntnu.tdt4240.project.engine.system.MovementSystem {
- PositionComponent pos
- VelocityComponent vel
- ImmutableArray<Entity> sabotageEntities
- ImmutableArray<Entity> powerupEntities
+ void addedToEngine(com.badlogic.ashley.core.Engine)
- void process(Entity,float)
+ void processEntity(Entity,float)
}


class no.ntnu.tdt4240.project.service.ScoreService {
- {static} String PREFS_NAME
- {static} String PREF_HIGH_SCORE
- {static} String PREF_ONLINE_WINS
- {static} ScoreService instance
- Preferences prefs
- int highScore
- int onlineWins
+ {static} ScoreService getInstance()
+ int getHighScore()
+ boolean updateHighScore(int)
+ int getOnlineWins()
+ void incrementOnlineWins()
}


class no.ntnu.tdt4240.project.state.TutorialState {
- {static} float VIEWPORT_MIN_WIDTH
- {static} float VIEWPORT_MIN_HEIGHT
- Stage stage
# void setup()
- void buildLayout()
+ void update(float)
# void render()
+ void resize(int,int)
+ void dispose()
}


class no.ntnu.tdt4240.project.service.FirebaseService {
- {static} FirebaseService instance
- String functionsBaseUrl
- String firestoreBaseUrl
- String databaseBaseUrl
- String projectId
- long serverTimeOffset
+ {static} void init()
+ {static} FirebaseService getInstance()
+ long getServerTime()
+ void fetchServerTimeOffset()
+ void getDbData(String,FirebaseCallback)
+ void putDbData(String,String,FirebaseCallback)
+ void patchDbData(String,String,FirebaseCallback)
+ void postDbData(String,String,FirebaseCallback)
+ void deleteDbData(String,FirebaseCallback)
+ void callGameHandler(String,String,String,FirebaseCallback)
+ void testConnection(FirebaseCallback)
+ void testFirestore(FirebaseCallback)
+ void testDatabase(FirebaseCallback)
- void sendRequest(String,String,String,FirebaseCallback)
}


interface no.ntnu.tdt4240.project.service.FirebaseService$FirebaseCallback {
~ void onSuccess(String)
~ void onFailure(String)
}

class no.ntnu.tdt4240.project.service.FirebaseService$ConnectivityProbe {
~ long ts
~ String source
}

class no.ntnu.tdt4240.project.model.LobbyPlayer {
+ String actualName
+ boolean inGameOverScreen
+ boolean gameOver
+ boolean leftLobby
+ Object lastTimeOnline
+ int personalHighScore
+ int score
+ Sabotage sabotage
+ String sabotageTargetId
}

class no.ntnu.tdt4240.project.engine.component.HealthComponent {
+ {static} float INVINCIBILITY_DURATION
+ int health
+ float invincibilityRemaining
+ boolean isInvincible()
}


class no.ntnu.tdt4240.project.engine.component.BulletComponent {
}
class no.ntnu.tdt4240.project.engine.entity.EntityAssembler {
- {static} float PLAYER_SHOOT_BASE_INTERVAL
- {static} float ENEMY_SHOOT_BASE_INTERVAL
- {static} float ANIMATION_FRAME_DURATION
- Engine engine
+ Entity create(Base)
+ void createPlayer(Playable)
+ void createPlayerBullet(NonPlayable)
+ void createEnemy(NonPlayable)
+ void createEnemyShooter(NonPlayable)
+ void createEnemyBullet(NonPlayable)
}


class no.ntnu.tdt4240.project.engine.system.CollisionSystem {
- Assets assets
- ImmutableArray<Entity> players
- ImmutableArray<Entity> playerBullets
- ImmutableArray<Entity> enemies
- ImmutableArray<Entity> enemyBullets
- ImmutableArray<Entity> powerupEntities
- ImmutableArray<Entity> waveEntities
+ void addedToEngine(Engine)
+ void update(float)
- void playerCollision(Entity,ImmutableArray<Entity>)
- void decrementEnemiesAlive()
- void enemyCollision(Entity,ImmutableArray<Entity>)
- void handleCollision(Entity,ImmutableArray<Entity>,BiConsumer<Entity,Entity>)
- boolean overlap()
- void setupRectangle1(Entity)
- void setupRectangle2(Entity)
- void setupRectangle(Entity,Rectangle)
- void resetRectangle()
}


class no.ntnu.tdt4240.project.engine.component.WaveComponent {
+ long seed
+ int waveNumber
+ int enemiesToSpawn
+ int enemiesAlive
+ float spawnInterval
+ float shooterChance
+ float enemySpeedMultiplier
+ boolean waveActive
+ float waveTransitionTimer
}

class no.ntnu.tdt4240.project.engine.component.VelocityComponent {
+ float x
}

class no.ntnu.tdt4240.project.GameInputProcessor {
- boolean touched
- float x
- float y
- Viewport viewport
- Vector2 tmpVec
- void unproject(int,int)
+ boolean touchDown(int,int,int,int)
+ boolean touchUp(int,int,int,int)
+ boolean touchDragged(int,int,int)
+ boolean isTouched()
+ float getX()
+ float getY()
}


class no.ntnu.tdt4240.project.engine.system.BoundSystem {
~ ImmutableArray<Entity> players
~ ImmutableArray<Entity> enemies
~ ImmutableArray<Entity> bullets
~ ImmutableArray<Entity> waveEntities
- PositionComponent pos
- DimensionComponent dim
+ void addedToEngine(Engine)
+ void update(float)
- void setup(Entity)
- void bulletOutOfBounds(Entity)
- void enemyOutOfBounds(Entity)
- boolean isOutOfBounds()
- boolean isOutOfTopBound()
- boolean isOutOfBottomBound()
- void decrementPlayerHealth()
}


class no.ntnu.tdt4240.project.config.Player {
- {static} float PLAYER_MARGIN_BOTTOM
- {static} float PLAYER_WIDTH
- {static} float PLAYER_HEIGHT
- {static} int HEALTH
- TextureRegion tex
- TextureRegion[] frames
+ Playable create()
- Vector2 calculatePosition(float)
}


class no.ntnu.tdt4240.project.data.Base {
+ Vector2 pos
+ TextureRegion tex
+ TextureRegion[] frames
}

class no.ntnu.tdt4240.project.model.Sabotage {
+ {static} String TYPE_ENEMY_SPEED
+ {static} String TYPE_HALF_PLAYER_BULLETS
+ {static} String TYPE_DOUBLE_ALIENS
+ String type
+ int duration
}

class no.ntnu.tdt4240.project.ui.view.GameHud {
- {static} float VIEWPORT_MIN_WIDTH
- {static} float VIEWPORT_MIN_HEIGHT
- {static} Color PAUSE_BUTTON_DISABLED_LABEL
- Stage stage
- Table menuPanel
- Texture overlayTex
- Label scoreLabel
- Label healthLabel
- Label waveLabel
- Label enemySpeedLabel
- Label fireRateLabel
- Label alienSpawnLabel
- Label shieldLabel
- Label rapidFireLabel
- Label slowEnemiesLabel
- TextButton sabotageButton
- TextButton powerupButton
- TextButton pauseButton
- Runnable onMenuResumePressed
- boolean isMenuOpen
+ void act(float,boolean,boolean,boolean,boolean,int,int,int,float,float,float,float,float,float)
- void updateEffectLabel(Label,String,float)
+ void draw()
+ Stage getStage()
+ void resize(int,int)
+ void dispose()
}


interface no.ntnu.tdt4240.project.ui.view.GameHud$MenuToggleListener {
~ void onMenuToggle(boolean)
}

interface no.ntnu.tdt4240.project.ui.view.GameHud$QuitListener {
~ void onQuit()
}

interface no.ntnu.tdt4240.project.ui.view.GameHud$PauseListener {
~ void onPause()
}

interface no.ntnu.tdt4240.project.ui.view.GameHud$SabotageListener {
~ void onSabotage()
}

interface no.ntnu.tdt4240.project.ui.view.GameHud$PowerupListener {
~ void onPowerup()
}

class no.ntnu.tdt4240.project.state.PauseState {
- {static} float VIEWPORT_MIN_WIDTH
- {static} float VIEWPORT_MIN_HEIGHT
- {static} float PAUSE_DURATION
- {static} float RETURN_BUTTON_HEIGHT
- {static} float RETURN_BOTTOM_PAD
- GameState gameState
- Stage stage
- Texture overlayTex
- float pauseTimeLeft
- Label timerLabel
# void setup()
# void show()
# void hide()
- void syncInputProcessor()
- void buildLayout()
- {static} String formatUnpauseTimer(float)
+ void update(float)
+ void render()
+ void resize(int,int)
+ void dispose()
}


class no.ntnu.tdt4240.project.sabotage.strategy.EnemySpeedSabotageStrategy {
+ void apply(SabotageEffectsComponent,float)
}

class no.ntnu.tdt4240.project.engine.component.ScoreComponent {
+ int score
}

class no.ntnu.tdt4240.project.service.LobbyService {
- String lobbyID
+ String lobbyUserID
- String playerID
- {static} String SERVER_TIMESTAMP
+ void checkDatabaseFormat(LobbyCallback)
+ void createDatabase(LobbyCallback)
+ void createLobby(LobbyCallback)
+ void joinLobby(String,LobbyCallback)
- LobbyPlayer createInitialLobbyPlayer()
+ void sendHeartbeat()
+ void updateScore(int)
+ void setPlayerGameOver(int)
+ void leaveLobby(LobbyCallback)
+ void startGame(LobbyCallback)
+ void setSabotage(Sabotage)
+ void delSabotage()
- void writeSabotage(Sabotage,String)
- String getSabotageTargetPlayerId(JsonValue)
+ void getLobbyStatus(LobbyStatusCallback)
+ void pingGameHandler()
+ void setPlayerID(String)
+ String getLobbyID()
}


interface no.ntnu.tdt4240.project.service.LobbyService$LobbyCallback {
~ void onSuccess(String)
~ void onFailure(String)
}

interface no.ntnu.tdt4240.project.service.LobbyService$LobbyStatusCallback {
~ void onUpdate(JsonValue)
~ void onFailure(String)
}

class no.ntnu.tdt4240.project.engine.component.DimensionComponent {
+ float width
}

interface no.ntnu.tdt4240.project.event.EventListener {
~ void receive(Event)
}

class no.ntnu.tdt4240.project.util.AppConfig {
- {static} AppConfig instance
+ String firebaseBaseUrl
+ String firestoreBaseUrl
+ String databaseBaseUrl
+ String projectId
+ {static} void init(AppConfig)
+ {static} AppConfig get()
}


class no.ntnu.tdt4240.project.state.MenuState {
- {static} float VIEWPORT_MIN_WIDTH
- {static} float VIEWPORT_MIN_HEIGHT
- {static} float BUTTON_SPACING
- Stage stage
# void setup()
- void buildLayout()
+ void update(float)
# void render()
+ void resize(int,int)
+ void dispose()
}


class no.ntnu.tdt4240.project.engine.component.PlayerComponent {
}
class no.ntnu.tdt4240.project.Main {
- SpriteBatch batch
- StateManager sm
- Assets assets
+ void create()
+ void render()
+ void resize(int,int)
+ void dispose()
}


class no.ntnu.tdt4240.project.state.GameOverState {
- {static} float VIEWPORT_MIN_WIDTH
- {static} float VIEWPORT_MIN_HEIGHT
- {static} float BUTTON_SPACING
- {static} float POLL_INTERVAL
- int finalScore
- Engine engine
- LobbyService lobbyService
- Stage stage
- boolean isNewHighScore
- Label titleLabel
- Table scoreboardTable
- float pollTimer
- boolean gameEndedDetected
- boolean winRecorded
- boolean isOnline()
# void setup()
- void buildSingleplayerLayout()
- void buildOnlineLayout()
- void updateScoreboard(JsonValue)
+ void update(float)
# void render()
+ void resize(int,int)
+ void dispose()
}




no.ntnu.tdt4240.project.powerup.strategy.PowerupStrategy <|.. no.ntnu.tdt4240.project.powerup.strategy.ShieldPowerupStrategy
no.ntnu.tdt4240.project.state.State <|-- no.ntnu.tdt4240.project.state.WaitingRoomState
no.ntnu.tdt4240.project.event.EventListener <|.. no.ntnu.tdt4240.project.state.GameState
no.ntnu.tdt4240.project.state.State <|-- no.ntnu.tdt4240.project.state.GameState
com.badlogic.ashley.systems.IteratingSystem <|-- no.ntnu.tdt4240.project.engine.system.RemovalSystem
no.ntnu.tdt4240.project.state.State <|-- no.ntnu.tdt4240.project.state.SettingsState
com.badlogic.ashley.core.Component <|.. no.ntnu.tdt4240.project.engine.component.EnemyComponent
no.ntnu.tdt4240.project.config.bullet.Bullet <|-- no.ntnu.tdt4240.project.config.bullet.EnemyBullet
com.badlogic.ashley.systems.IteratingSystem <|-- no.ntnu.tdt4240.project.engine.system.ShootingSystem
no.ntnu.tdt4240.project.state.State <|-- no.ntnu.tdt4240.project.state.LeaderboardState
no.ntnu.tdt4240.project.state.State <|-- no.ntnu.tdt4240.project.state.PowerupState
com.badlogic.ashley.systems.IteratingSystem <|-- no.ntnu.tdt4240.project.engine.system.WaveSystem
no.ntnu.tdt4240.project.state.State <|-- no.ntnu.tdt4240.project.state.SabotageState
no.ntnu.tdt4240.project.sabotage.strategy.SabotageStrategy <|.. no.ntnu.tdt4240.project.sabotage.strategy.DoubleAliensSabotageStrategy
com.badlogic.ashley.core.Component <|.. no.ntnu.tdt4240.project.engine.component.PowerupEffectsComponent
no.ntnu.tdt4240.project.state.State <|-- no.ntnu.tdt4240.project.state.HistoryState
com.badlogic.ashley.core.Component <|.. no.ntnu.tdt4240.project.engine.component.SabotageEffectsComponent
no.ntnu.tdt4240.project.data.Base <|-- no.ntnu.tdt4240.project.data.Playable
no.ntnu.tdt4240.project.sabotage.strategy.SabotageStrategy <|.. no.ntnu.tdt4240.project.sabotage.strategy.HalfPlayerBulletsSabotageStrategy
com.badlogic.ashley.systems.IteratingSystem <|-- no.ntnu.tdt4240.project.engine.system.PowerupEffectSystem
com.badlogic.ashley.core.Component <|.. no.ntnu.tdt4240.project.engine.component.TextureComponent
com.badlogic.ashley.core.EntitySystem <|-- no.ntnu.tdt4240.project.engine.system.BounceSystem
com.badlogic.ashley.core.Component <|.. no.ntnu.tdt4240.project.engine.component.AnimationComponent
com.badlogic.ashley.systems.IteratingSystem <|-- no.ntnu.tdt4240.project.engine.system.EventSystem
no.ntnu.tdt4240.project.layout.Layout <|-- no.ntnu.tdt4240.project.layout.GameLayout
no.ntnu.tdt4240.project.config.bullet.Bullet <|-- no.ntnu.tdt4240.project.config.bullet.PlayerBullet
no.ntnu.tdt4240.project.powerup.strategy.PowerupStrategy <|.. no.ntnu.tdt4240.project.powerup.strategy.SlowEnemiesPowerupStrategy
com.badlogic.gdx.scenes.scene2d.ui.TextButton <|-- no.ntnu.tdt4240.project.ui.SpaceButton
com.badlogic.ashley.core.Component <|.. no.ntnu.tdt4240.project.engine.component.RemoveComponent
com.badlogic.ashley.core.Component <|.. no.ntnu.tdt4240.project.engine.component.ShooterComponent
com.badlogic.ashley.core.EntitySystem <|-- no.ntnu.tdt4240.project.engine.system.SpawnSystem
com.badlogic.ashley.core.Component <|.. no.ntnu.tdt4240.project.engine.component.PositionComponent
com.badlogic.gdx.scenes.scene2d.ui.Table <|-- no.ntnu.tdt4240.project.ui.FirebaseTestWidget
no.ntnu.tdt4240.project.data.Base <|-- no.ntnu.tdt4240.project.data.NonPlayable
com.badlogic.ashley.systems.IteratingSystem <|-- no.ntnu.tdt4240.project.engine.system.SabotageEffectSystem
no.ntnu.tdt4240.project.powerup.strategy.PowerupStrategy <|.. no.ntnu.tdt4240.project.powerup.strategy.RapidFirePowerupStrategy
com.badlogic.ashley.systems.IteratingSystem <|-- no.ntnu.tdt4240.project.engine.system.RenderSystem
com.badlogic.ashley.systems.IteratingSystem <|-- no.ntnu.tdt4240.project.engine.system.InputSystem
com.badlogic.ashley.systems.IteratingSystem <|-- no.ntnu.tdt4240.project.engine.system.MovementSystem
no.ntnu.tdt4240.project.state.State <|-- no.ntnu.tdt4240.project.state.TutorialState
no.ntnu.tdt4240.project.service.FirebaseService +.. no.ntnu.tdt4240.project.service.FirebaseService$FirebaseCallback
no.ntnu.tdt4240.project.service.FirebaseService +.. no.ntnu.tdt4240.project.service.FirebaseService$ConnectivityProbe
com.badlogic.ashley.core.Component <|.. no.ntnu.tdt4240.project.engine.component.HealthComponent
com.badlogic.ashley.core.Component <|.. no.ntnu.tdt4240.project.engine.component.BulletComponent
com.badlogic.ashley.core.EntitySystem <|-- no.ntnu.tdt4240.project.engine.system.CollisionSystem
com.badlogic.ashley.core.Component <|.. no.ntnu.tdt4240.project.engine.component.WaveComponent
com.badlogic.ashley.core.Component <|.. no.ntnu.tdt4240.project.engine.component.VelocityComponent
com.badlogic.gdx.InputAdapter <|-- no.ntnu.tdt4240.project.GameInputProcessor
com.badlogic.ashley.core.EntitySystem <|-- no.ntnu.tdt4240.project.engine.system.BoundSystem
no.ntnu.tdt4240.project.ui.view.GameHud +.. no.ntnu.tdt4240.project.ui.view.GameHud$MenuToggleListener
no.ntnu.tdt4240.project.ui.view.GameHud +.. no.ntnu.tdt4240.project.ui.view.GameHud$QuitListener
no.ntnu.tdt4240.project.ui.view.GameHud +.. no.ntnu.tdt4240.project.ui.view.GameHud$PauseListener
no.ntnu.tdt4240.project.ui.view.GameHud +.. no.ntnu.tdt4240.project.ui.view.GameHud$SabotageListener
no.ntnu.tdt4240.project.ui.view.GameHud +.. no.ntnu.tdt4240.project.ui.view.GameHud$PowerupListener
no.ntnu.tdt4240.project.state.State <|-- no.ntnu.tdt4240.project.state.PauseState
no.ntnu.tdt4240.project.sabotage.strategy.SabotageStrategy <|.. no.ntnu.tdt4240.project.sabotage.strategy.EnemySpeedSabotageStrategy
com.badlogic.ashley.core.Component <|.. no.ntnu.tdt4240.project.engine.component.ScoreComponent
no.ntnu.tdt4240.project.service.LobbyService +.. no.ntnu.tdt4240.project.service.LobbyService$LobbyCallback
no.ntnu.tdt4240.project.service.LobbyService +.. no.ntnu.tdt4240.project.service.LobbyService$LobbyStatusCallback
com.badlogic.ashley.core.Component <|.. no.ntnu.tdt4240.project.engine.component.DimensionComponent
no.ntnu.tdt4240.project.state.State <|-- no.ntnu.tdt4240.project.state.MenuState
com.badlogic.ashley.core.Component <|.. no.ntnu.tdt4240.project.engine.component.PlayerComponent
com.badlogic.gdx.ApplicationAdapter <|-- no.ntnu.tdt4240.project.Main
no.ntnu.tdt4240.project.state.State <|-- no.ntnu.tdt4240.project.state.GameOverState
@enduml