@startuml
set separator none

package no.ntnu.tdt4240.project.engine.entity {

class EntityAssembler {
- {static} float PLAYER_SHOOT_BASE_INTERVAL
- {static} float ENEMY_SHOOT_BASE_INTERVAL
- {static} float ANIMATION_FRAME_DURATION
- Engine engine0
+ Entity create(Base)
+ void createPlayer(Playable)
+ void createPlayerBullet(NonPlayable)
+ void createEnemy(NonPlayable)
+ void createEnemyShooter(NonPlayable)
+ void createEnemyBullet(NonPlayable)
}

}

@enduml